name = "Pulseback"
client_id = "0ff9e7f487dd70fd194d572484f7f0c8"
application_url = "https://pulseback.fly.dev"
embedded = false

[access_scopes]
scopes = "write_customers,write_orders,write_products,read_checkouts"

[auth]
redirect_urls = [
  "https://pulseback.fly.dev/auth/callback",
  "https://pulseback.fly.dev/auth/shopify/callback",
  "https://pulseback.fly.dev/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
